apiVersion: v1
kind: PersistentVolume
metadata:
  name: work-tracker-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/kubernetes_files/helm_charts/work-tracker/main/volumes/sqlite_db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: work-tracker-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
